parameter_definition:
  livetime:
    nominal_value: 365.
    ptype: livetime
    fittable: false
    description: Livetime in day

  xe133_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1000

  xe136_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1000

  test_flat_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: ture
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1000

  test_gaussian_rate_multiplier:
    nominal_value: 300
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 300

  smearing_a:
    nominal_value: 24.8
    ptype: shape
    uncertainty: 0.1
    relative_uncertainty: false
    fittable: false
    blueice_anchors:
      - 24.8
    fit_limits:
      - 20
      - 30
    description: smearing shaping parameter

  smearing_b:
    nominal_value: 1.429
    ptype: shape
    uncertainty: 0.05
    relative_uncertainty: false
    fittable: false
    blueice_anchors:
      - 1.429
    fit_limits:
      - 1.2
      - 1.6
    description: smearing shaping parameter

  efficiency_constant:
    nominal_value: 0.8
    ptype: shape
    uncertainty: 0.05
    relative_uncertainty: false
    fittable: ture
    blueice_anchors:
      - 0.7
      - 0.9

likelihood_config:
  template_folder: null  # will try to find the templates in alea
  likelihood_terms:
    - name: science_run_0
      default_source_class: alea.ces_source.CESTemplateSource
      likelihood_type: blueice.likelihood.BinnedLogLikelihood
      analysis_space:
        - ces: np.arange(0, 1000, 1)
      # smearing and efficiency are applied to all of the sources, unless overridden
      apply_efficiency: true
      efficiency_model: constant
      efficiency_parameters:
        - efficiency_constant
      apply_smearing: true
      smearing_model: gaussian
      smearing_parameters:
        - smearing_a
        - smearing_b
      apply_bias: false
      livetime_parameter: livetime
      slice_args: {}
      source_wise_interpolation: false
      sources:
      - name: xe133
        histname: xe133_template
        parameters:
          - xe133_rate_multiplier
          - smearing_a
          - smearing_b
          - efficiency_constant
        template_filename: xe133_template.ii.h5
      - name: xe136
        histname: xe136_hsd
        parameters:
          - xe136_rate_multiplier
          - smearing_a
          - smearing_b
          - efficiency_constant
        template_filename: xe136_template.ii.h5
      - name: test_gaussian
        class: alea.ces_source.CESMonoenergySource
        peak_energy: 300
        parameters:
          - test_gaussian_rate_multiplier
          - smearing_a
          - smearing_b
          - efficiency_constant
      - name: test_flat
        class: alea.ces_source.CESFlatSource
        parameters:
          - test_flat_rate_multiplier
          - efficiency_constant
