parameter_definition:
  livetime:
    nominal_value: 365.
    ptype: livetime
    fittable: false
    description: Livetime in day

  xe133_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1.0
  
  test_flat_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: ture
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0 
      - 50
    fit_guess: 1.0

  test_gaussian_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1.0

  smearing_a:
    nominal_value: 24.8
    ptype: shape
    uncertainty: 0.1
    relative_uncertainty: false
    fittable: true
    blueice_anchors:
      - 0
      - 20
      - 24.8
      - 30
      - 100
    fit_limits:
      - 0
      - 100
    description: smearing shaping parameter

  smearing_b:
    nominal_value: 1.429
    ptype: shape
    uncertainty: null
    fittable: true
    blueice_anchors:
      - 1.0
      - 1.429
      - 2.0
    fit_limits:
      - 1.0
      - 2.0
    description: smearing shaping parameter

likelihood_config:
  template_folder: null  # will try to find the templates in alea
  likelihood_terms:
    - name: science_run_0
      default_source_class: alea.ces_source.CESTemplateSource
      likelihood_type: blueice.likelihood.UnbinnedLogLikelihood
      analysis_space:
        - ces: np.arange(0, 3000, 1)
      # smearing and efficiency are applied to all of the sources, unless overridden
      apply_efficiency: false
      efficiency_model: constant
      efficiency_parameters:
        - efficiency
      apply_smearing: true
      smearing_model: gaussian
      smearing_parameters:
        - smearing_a
        - smearing_b
      apply_bias: false
      livetime_parameter: livetime
      slice_args: {}
      sources:
      - name: xe133
        histname: xe133_template
        parameters:
          - xe133_rate_multiplier
          - smearing_a
          - smearing_b
        template_filename: xe133_template.ii.h5
      - name: test_flat
        class: alea.ces_source.CESFlatSource
        parameters:
          - test_flat_rate_multiplier
      - name: test_gaussian
        class: alea.ces_source.CESGaussianSource
        peak_energy: 1500
        parameters:
          - test_gaussian_rate_multiplier
          - smearing_a
          - smearing_b



