parameter_definition:
  livetime:
    nominal_value: 2.
    ptype: livetime
    fittable: false
    description: Livetime in years

  signal_rate_multiplier:
    nominal_value: 1.0
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50

  background_rate_multiplier:
    nominal_value: 1.0
    ptype: rate
    uncertainty: 0.2
    relative_uncertainty: true
    fittable: true
    fit_limits:
      - 0
      - null
    fit_guess: 1.0

  eff_parameter:
    nominal_value: 0
    ptype: shape
    uncertainty: null
    fittable: true
    blueice_anchors:
      - -2
      - -1
      - 0
      - 1
      - 2
    fit_limits:
      - -2
      - 2
    description: efficiency shaping parameter

likelihood_config:
  template_folder: null  # will try to find the templates in alea
  likelihood_terms:
    - name: science_run
      default_source_class: alea.template_source.CESTemplateSource
      likelihood_type: blueice.likelihood.UnbinnedLogLikelihood
      analysis_space:
        - ces: np.arange(0, 100, 1)
      in_events_per_bin: true
      livetime_parameter: livetime
      slice_args: {}
      sources:
      - name: background
        histname: ces_background_template
        parameters:
          - background_rate_multiplier
          - eff_parameter
        template_filename: ces_background_template.ii.h5

      - name: signal
        histname: ces_signal_template
        parameters:
          - signal_rate_multiplier
          - eff_parameter
        template_filename: ces_signal_template.ii.h5

