parameter_definition:
  livetime:
    nominal_value: 365.
    ptype: livetime
    fittable: false
    description: Livetime in day

  fiducial_mass:
    nominal_value: 4
    ptype: needs_reinit
    fittable: false
    description: Fiducial mass in ton

  xe133_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1000

  test_flat_rate_multiplier:
    nominal_value: 1000
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 1000

  test_gaussian_rate_multiplier:
    nominal_value: 300
    ptype: rate
    fittable: true
    fit_limits:
      - 0
      - null
    parameter_interval_bounds:
      - 0
      - 50
    fit_guess: 300

  smearing_a:
    nominal_value: 24.8
    ptype: shape
    uncertainty: 0.1
    relative_uncertainty: false
    fittable: true
    blueice_anchors:
      - 20
      - 24.8
      - 30
    fit_limits:
      - 20
      - 30
    description: smearing shaping parameter

  smearing_b:
    nominal_value: 1.429
    ptype: shape
    uncertainty: 0.05
    relative_uncertainty: false
    fittable: true
    blueice_anchors:
      - 1.2
      - 1.429
      - 1.6
    fit_limits:
      - 1.2
      - 1.6
    description: smearing shaping parameter

  efficiency_constant:
    nominal_value: 0.8
    ptype: shape
    uncertainty: 0.05
    relative_uncertainty: false
    fittable: true
    blueice_anchors:
      - 0.7
      - 0.9

  A:
    nominal_value: 0.01977
    ptype: shape
    uncertainty: 0.001
    relative_uncertainty: false
    fittable: false
    blueice_anchors:
      - 0.01977
    description: bais shaping parameter

  k:
    nominal_value: 0.01707
    ptype: shape
    uncertainty: 0.001
    relative_uncertainty: false
    fittable: false
    blueice_anchors:
      - 0.01707
    description: bias shaping parameter

  B:
    nominal_value: 0.0
    ptype: shape
    uncertainty: 0.01
    relative_uncertainty: false
    fittable: true
    blueice_anchors:
      - -0.02
      - 0.0
      - 0.02
    fit_limits:
      - -0.02
      - 0.02
    description: bias shaping parameter

likelihood_config:
  template_folder: null  # will try to find the templates in alea
  likelihood_terms:
    - name: science_run_0
      default_source_class: alea.ces_source.CESTemplateSource
      likelihood_type: blueice.likelihood.UnbinnedLogLikelihood
      analysis_space:
        - ces: np.arange(0, 500, 1)
      minimal_energy_resolution: 0.1
      # smearing and efficiency are applied to all of the sources, unless overridden
      apply_efficiency: true
      efficiency_model: constant
      efficiency_parameters:
        - efficiency_constant
      apply_smearing: true
      smearing_model: gaussian
      smearing_parameters:
        - smearing_a
        - smearing_b
      apply_bias: true
      bias_model: arctan
      bias_parameters:
        - A
        - k
        - B
      livetime_parameter: livetime
      fiducial_mass_parameter: fiducial_mass
      slice_args: {}
      sources:
      - name: xe133
        histname: xe133_template
        parameters:
          - xe133_rate_multiplier
          - smearing_a
          - smearing_b
          - efficiency_constant
          - A
          - k
          - B
        template_filename: xe133_template.ii.h5
      - name: test_gaussian
        class: alea.ces_source.CESMonoenergySource
        peak_energy: 300
        parameters:
          - test_gaussian_rate_multiplier
          - smearing_a
          - smearing_b
          - efficiency_constant
          - A
          - k
          - B
      - name: test_flat
        class: alea.ces_source.CESFlatSource
        parameters:
          - test_flat_rate_multiplier
          - efficiency_constant
